services:
  app:
    build: ./docker/php
    ports:
      - 5173:5173
    volumes:
      - ./src:/data:delegated,uid=1000,gid=1000
      - ./src:/data

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
